build: inject wasm base64 into build_index.sh script
spaceandtimelabs/sxt-proof-of-sql-sdk pull request #41
Opened 2024-11-22 22:36 UTC by Dustin-Ray

# Rationale for this change

Updates the build script to truncate off portions of the glue code generated from wasm-pack, injects base64 wasm from the sxt-verifier, then appends wasm instantiation code to the file index. js which is ultimately produced

# What changes are included in this PR?

updates to build_index.js 

# Are these changes tested?

yes

2024-11-22 23:11 UTC, tlovell-sxt commented on node/src/package.json
> +    "version": "1.0.0",
Could this be set to 0.2.0? Just so that it's in sync with the versioning of the release CI

2024-11-22 23:11 UTC, tlovell-sxt commented on node/src/build_index.sh
> +    local output_js_file="index.js"
So if we want to avoid disturbing the CI, I believe this needs to be runnable from the root of the repository, and accept a path to the pkg location.

Something like...
```suggestion
    local input_js_file="$1/sxt_proof_of_sql_sdk_wasm.js"
    local wasm_file="$1/sxt_proof_of_sql_sdk_wasm_bg.wasm"
    local output_js_file="$SCRIPT_DIR/index.js"
```

2024-11-22 23:11 UTC, tlovell-sxt commented on node/src/build_index.sh
>  cp $1/sxt_proof_of_sql_sdk_wasm_bg.wasm $SCRIPT_DIR
I believe this can be removed now 
```suggestion
```

Though, I guess it may need to be removed as an artifact of the release CI if we do that

2024-11-22 23:11 UTC, tlovell-sxt commented on node/src/build_index.sh
>  cat $1/sxt_proof_of_sql_sdk_wasm.js $SCRIPT_DIR/index_tail.js > $SCRIPT_DIR/index.js
Might as well put this line in the main function now, since it will reuse some of the paths defined there

2024-11-22 23:52 UTC, tlovell-sxt commented on node/src/build_index.sh
> +    cat $1/sxt_proof_of_sql_sdk_wasm.js $SCRIPT_DIR/index_tail.js > $SCRIPT_DIR/index.js
```suggestion
    cp $output_js_file $output_js_file.tmp

    cat $output_js_file.tmp $SCRIPT_DIR/index_tail.js > $output_js_file

    rm $output_js_file.tmp

    echo "Modified JavaScript file created: $output_js_file"
```

2024-11-22 23:52 UTC, tlovell-sxt commented on node/src/package.json
> +}
In the `.github/workflows/release.yml`, could you update the `artifacts` to not upload the .wasm file?

2024-11-22 23:58 UTC, tlovell-sxt commented on .github/workflows/release.yml
>            makeLatest: true
```suggestion
          artifacts: "node/src/index.js"
          makeLatest: true
```

2024-11-23 00:00 UTC, tlovell-sxt approved these changes
Squash merge this or pre-squash some of these commits

2024-11-23 00:01 UTC, tlovell-sxt requested changes
Actually, since this repo has automerge I think you have to pre-squash some of these commits. I think the repo title/description would be good

2024-11-23 00:08 UTC, tlovell-sxt commented on node/src/package.json
> +{
I think this needs to be in the `node` directory, not `node/src`

2024-11-23 01:58 UTC, JayWhite2357 commented
> Actually, since this repo has automerge I think you have to pre-squash some of these commits. I think the repo title/description would be good

You could just disable auto-merge and then squash merge. Just don't approve it if you're requesting a squash merge, or it will get auto merged.

2024-11-23 02:01 UTC, JayWhite2357 commented on node/src/build_index.sh
> +    echo "let wasmCode = \`$base64_wasm\`;" >> "$js_file"
NIT
```suggestion
    echo "const wasmCode = \`$base64_wasm\`;" >> "$js_file"
```

2024-11-23 02:07 UTC, JayWhite2357 commented on node/src/build_index.sh
> +    if ! sed '/^const wasm_url = new URL('\''sxt_proof_of_sql_sdk_wasm_bg.wasm'\'', import.meta.url);/,$d' "$input_js_file" > "$output_js_file"; then
NIT:
Might be more robust to only match on a portion of this.
Perhaps just the `const wasm_url = new URL` portion in case we want to rename the crate/wasm file.
Not sure if that would work, and we can always add it in a later PR.

2024-11-23 02:14 UTC, tlovell-sxt approved these changes

2024-11-23 02:14 UTC, merged